# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8656cbd340bcef7ecf3b4f95b42de46aeeff06b1033addbf45015bb7c36830686b1422237bf3be8cd514420ab0ad58e4954bbee8340eeb2f0d9e54e5ada8b0b

test:
  secret_key_base: 0661426131b6d95780ca4692aadc18b6a4348c3cf0f451da0e6ab8a9af83ef9da0214b2523941e37dba18fecb7579f1a4d82fbc8cf3ccd58f98e6e99d85d0798

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
